### PR TITLE
Added MangaKatana connector

### PR DESCRIPTION
**Pull request by arxae**

### CODE REVIEW

**Review by C9Glax — CHANGES_REQUESTED** [review]
Hey there, already great work, looks like I have to take a closer look at HTMLAgilityPack, since my Mangasee uses a headless browser instead, and that makes things a lot more bloated, your solution seems a lot cleaner.
Also love the check to see if a site actually exists. Will probably update existing connectors to use that as well.

Just 2 or 3 minor things I would like changed/improved:
- Remove commented code (Lines 77 and 80)
- I took a glance at the site, and couldn't find any releases with volume-numbers attached. If there aren't just remove the parsing from line 161 and replace it with null
- Line 144 `return chapters.OrderBy(chapter => Convert.ToSingle(chapter.chapterNumber, chapterNumberFormatInfo)).ToArray();` and Line 168 `ret.Reverse();` would have the same result, maybe just remove the `Reverse()` call?

And an even pettier thing: The identation in TaskManager is 8 instead of 4 spaces 😜 

Thanks for your contribution!

**Comment by arxae** [comment]
I made the required changes. Some things i just overlooked some things apparently :P 

But in my defense

> Line 144 return chapters.OrderBy(chapter => Convert.ToSingle(chapter.chapterNumber, chapterNumberFormatInfo)).ToArray(); and Line 168 ret.Reverse(); would have the same result, maybe just remove the Reverse() call?

I took the Manganato connector as a base and just went from there. I haven't touched that part, so it's actually your code :P  But I have removed the line as well

**Comment by C9Glax** [comment]
> I took the Manganato connector as a base and just went from there. I haven't touched that part, so it's actually your code :P

Couldn't be my mistake ;)

**Comment by C9Glax** [comment]
@arxae Am I stupid or what is going on?
I merged the PR but it's not showing up?

**Review by C9Glax — COMMENTED** [review]
thx

**Comment by arxae** [comment]
No, you're not stupid. I noticed the same, but i thought github was having some delay or something. I'll open a new pull request and hope that one works

**Pull request merged**
