### PR TITLE
Automatic build of Docker images for many platforms (ARM too)

### PR DESCRIPTION
**Pull request by schklom**
Solves https://github.com/C9Glax/tranga/issues/6?

## IMPORTANT
Make sure to setup [personal access tokens](https://docs.docker.com/docker-hub/access-tokens/) `DOCKERHUB_USERNAME` and `DOCKERHUB_TOKEN` as documented on https://github.com/docker/login-action#docker-hub

This will build Docker images of base, website, api, on pushes and pulls on your master branch, and you can trigger a build manually in the `Action` tab of this repo (https://github.com/C9Glax/tranga/actions).

### CODE REVIEW

**Comment by schklom** [comment]
I did not try to build this repo yet, but this can automate building+deploying for many platforms at once.

**Comment by C9Glax** [comment]
Okay automatic builds is something I have wanted for a long time now.
I just haven't tested, wether I use any architecture features, that would stop us from building on for example ARM.
Brb, gotta push some code and test this :P

**Review by C9Glax — APPROVED** [review]

**Comment by schklom** [comment]
Testing on the master branch? I also like to live dangerously :D

PS: I forgot to remove it, but this code also adds a build on `linux/386`. Remove that if it fails, it is not a very popular platform anyway.

**Comment by C9Glax** [comment]
Yeah just gotta change that now to develop on dev.
If its a one-man army, idc if I develop on master :)

And yeah building fails on 386, but also on arm, because .net core is not officially supporting arm...
So making changes as we speak :)

**Comment by C9Glax** [comment]
Okay got it working, but only after removing all architectures apart from amd64 

`Assertion failed: (dc->base.pc_next & 1) == 0 (../target/arm/translate.c: thumb_tr_translate_insn: 9650)`
fails on arm sadly, so wont be able to build for arm :(

**Comment by C9Glax** [comment]
Thanks for pushing the automatic builds. Wouldn't have done it for ages, because I had no idea how "easy" it actually seems to be.

**Pull request merged**
